# Generated by Django 5.1.6 on 2025-02-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokepedia', '0002_pokemon_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='genus',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
