# Generated by Django 5.1.6 on 2025-02-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokepedia', '0003_pokemon_genus'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='evolutions',
            field=models.ManyToManyField(to='pokepedia.pokemon'),
        ),
    ]
