# Generated by Django 5.1.6 on 2025-02-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokepedia', '0005_alter_pokemon_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='evolutions',
            field=models.ManyToManyField(null=True, to='pokepedia.pokemon'),
        ),
    ]
